#pragma once
//i like to put my variables in here because it makes me look like big haxor :sun_glasses:
#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>
#include <stdint.h>
#include <inttypes.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <unistd.h>
#include <time.h>
#include <fcntl.h>
#include <sys/epoll.h>
#include <errno.h>
#include <pthread.h>
#include <signal.h>
#include <arpa/inet.h>
#include <err.h> 
#include <ctype.h> 
#include <net/if.h> 
#include <dirent.h>
#include <sys/ioctl.h>
#include <netinet/in.h>
#include <linux/limits.h>