#!/bin/bash
while :
do
#SMU Random Infinite Class
#################################
RANGE=254
number=$RANDOM
number2=$RANDOM
let "number %= $RANGE"
let "number2 %= $RANGE"
#################################
./go $number.$number2
done
