#!/bin/bash
if [ $# != 1 ]; then
        echo " usage: $0 <b class>"
        exit;
fi

rm -rf scan.log mfu.txt 1>/dev/null 2>/dev/null
echo -e "              \033[1;33m\033[1;32m    PlTBuLL \033[1;33m\033[0m"
echo -e "          \033[1;33m\033[1;32m  FRESH From #MaStErHaCk \033[1;33m\033[0m"
././pscan2 $1 22 

sleep 10
mv scan.log bios.txt
oopsnr2=`grep -c . bios.txt`
echo -e "**  \033[1;33m          ... incepem ...     \033[0m   **"
export PATH=.:$PATH
hald
rm -rf scan.log mfu.txt 1>/dev/null 2>/dev/null
echo "##        asta a fost, baga clasa urmatoare         ##"
