#!/bin/bash

BLK='[1;30m'
RED='[1;31m'
GRN='[1;32m'
YEL='[1;33m'
BLU='[1;34m'
MAG='[1;35m'
CYN='[1;36m'
WHI='[1;37m'
DRED='[0;31m'
DGRN='[0;32m'
DYEL='[0;33m'
DBLU='[0;34m'
DMAG='[0;35m'
DCYN='[0;36m'
DWHI='[0;37m'
RES='[0m'

echo "${DYEL}[${DRED}*${DYEL}]${DRED} SEARCH... ${DRED} "
if [ -e classes/$1 ] ; then
        echo "${DYEL}[${DRED}*${DYEL}]${DRED} Cautam database : ${DGRN}FIX ${RES}"
		echo "${DYEL}[${DRED}*${DYEL}]${DRED} Cautam clasele B: ${DGRN}FIX${RES}"
		sleep 3
		oopsnr2=`grep -c . classes/$1`
		echo "${DYEL}[${DRED}*${DYEL}]${DRED} Am gasit ->${DGRN} $oopsnr2 ${RED}de clase B ${RES}"
		sleep 5
		./range classes/$1
else
        echo "${WHI}[${RED}*${WHI}] NOT FOUND DB. TYPE ./lst FOR COUNTRY LIST. ${RES}"
fi
