#!/bin/bash

BLK='[1;30m'
RED='[1;31m'
GRN='[1;32m'
YEL='[1;33m'
BLU='[1;34m'
MAG='[1;35m'
CYN='[1;36m'
WHI='[1;37m'
DRED='[0;31m'
DGRN='[0;32m'
DYEL='[0;33m'
DBLU='[0;34m'
DMAG='[0;35m'
DCYN='[0;36m'
DWHI='[0;37m'
RES='[0m'
printf "${YEL}Folsim comanda \"cat .ez\" ca sa vezi lista de porturi\n" 
sleep 5
if [ -e .clase/$1 ] ; then
		echo "${BLK}>>>${YEL} Cautam............"
		sleep 3
		oopsnr2=`grep -c . .clase/$1`
		echo "${BLK}>>>${YEL} Am gasit ->${DGRN} $oopsnr2 ${YEL} porturi ${YEL}"
		sleep 5
		./range .clase/$1
else
        echo "${BLK}>>>${RED} Nu am gasit fisierul cu clase ${YEL}"
fi
